### ISSUE TITLE
New release with latest ytt

### ISSUE THREAD

**Issue by phil9909** [k14s/kapp-controller#1]
I'm depending on a ytt feature added in [0.23.0](https://github.com/k14s/ytt/releases/tag/v0.23.0) (released shortly after the first and only kapp-controller release).

Please rebuild the docker-image https://github.com/k14s/kapp-controller/blob/a4a1e6491218350e71c5c149c3ff8a9d6363d0de/Dockerfile#L7

and create a new release.

**Comment by phil9909** [comment]
If someone runs into the same problem: feel free to use `index.docker.io/phil9909/kapp-controller@sha256:911cbedd9749dd29fed77fefd57aaf0de5a397a68d9838aa0ed6aca2631a6b06` until a new release it there.

**Comment by cppforlife** [comment]
published https://github.com/k14s/kapp-controller/releases/tag/v0.2.0
