### ISSUE TITLE
App should support multiple fetch directives

### ISSUE THREAD

**Issue by jkbschmid** [k14s/kapp-controller#14]
In the App CR, the documentation states that `Fetch must have one *or more* directives`. However, when specifying multiple fetch directives (e.g. two directives of type `git`) only the last one is used. This is because of https://github.com/k14s/kapp-controller/blob/17b8d5d7e6b25bd382b94146511bbb7908fe9913/pkg/app/app_fetch.go#L79 (Extract empties the dstPath before copying).

**Comment by cppforlife** [comment]
i'd like to block this functionality on https://github.com/k14s/kapp-controller/issues/12. with vendir there would be more control over how configuration is extracted.

**Comment by loewenstein** [comment]
I am all for code reuse and limiting duplication. However, if I look at the Vendir and App CR, I see a significant difference of supported fetch configurations.

Vendir seems to essentially support fetching from Git and GitHub releases, for re-use in kapp-controller I don't count copying of local directories. 
The App CR is lacks support of GitHub releases, but has support for ConfigMap, Secret, Image, HTTP and Helm Chart repos.

Given the quick fix provided with #15 could be slightly modified to at least not break the Helm case (but essentially documenting a limitation on exactly one Helm Chart fetch directive), would you consider (or re-consider) taking a fix until Vendir _does_ have support for at least the fetch configurations that the current App CR supports?

**Comment by cppforlife** [comment]
im not opposed to pulling it for now _if_ it would deal with one fetch (no extra subdirs) vs multiple fetches (uses subdirs). im also not comfortable keeping numeric subdirs once vendir change is pulled in. if yall are ok with that, we can pull it in.

**Comment by phil9909** [comment]
I added a check to not use subfolders, if there is one fetch https://github.com/k14s/kapp-controller/pull/15/commits/a8a2c1dcbfa76c66e5a92e67f4e0d90c26213936 and an e2e test https://github.com/k14s/kapp-controller/pull/15/commits/cabbfac76c30bcd90b06a822a55fc2906fa078c7 to the PR #15.

> im not opposed to pulling it for now _if_ it would deal with one fetch (no extra subdirs) vs multiple fetches (uses subdirs). im also not comfortable keeping numeric subdirs once vendir change is pulled in. if yall are ok with that, we can pull it in.

I'm fine with that.

**Comment by loewenstein** [comment]
>  im also not comfortable keeping numeric subdirs once vendir change is pulled in

Vendir will give users control over where things are pulled, correct?

**Comment by cppforlife** [comment]
> Vendir will give users control over where things are pulled, correct?

that's the plan so far. we'll have to figure exactly how we can nicely incorporate vendir configuration into fetch section without adding complexity for common case of pulling in single thing.

**Comment by cppforlife** [comment]
included in https://github.com/k14s/kapp-controller/releases/tag/v0.7.0
